name: Parsers test

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/main/kotlin/org/manganga/mobile/parsers/site/*'

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'
      - run: ./gradlew :test --tests "org.manganga.mobile.parsers.MangaParserTest" || true
      - run: ./gradlew generateTestsReport
      - uses: actions/upload-artifact@v3
        with:
          name: Report
          path: build/test-results-html/TEST-org.manganga.mobile.parsers.MangaParserTest.htm